import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
        <body className={`bg-gray-900 ${inter.className} flex flex-col min-h-screen`}>
            <Header />
            <div className='mx-auto max-w-7xl px-4 py-24 sm:px-6 lg:px-8 flex-grow w-full'>
                {children}
            </div>
            <Footer />
        </body>
    </html>
  )
}